# Generated by Django 3.2.5 on 2021-08-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_processed', 'Not Processed'), ('processed', 'Processed'), ('shipping', 'Shipping'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='not_processed', max_length=50),
        ),
    ]
